language: cpp

matrix:
  include:

    - os: linux
      dist: xenial
      compiler: gcc

    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages: ['clang-6.0', 'libstdc++-8-dev']

    - os: osx
      compiler: gcc

    - os: osx
      compiler: clang

    - os: windows

install:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make -j 4
#  - sudo make install
  - cd ..

script:
  - cd build/bin
  - ./prjmodel_tests
  
